version: '3.8'

services:

  servicio2:
    build: ./servicio2
    ports:
      - "5001:5000"
    networks:
      - app-network

  jenkins:
    build: ./jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:

volumes:
  jenkins-data:
